GET http://localhost:8080/bodegas

###

GET http://localhost:8080/bodega/2

###

POST http://localhost:8080/bodega
Content-Type: application/json

{
    "nombre": "test",
    "direccion": "test"

}

###

put http://localhost:8080/bodega/2
Content-Type: application/json

{
    "nombre": "test",
    "direccion": "test"

}

###

DELETE http://localhost:8080/bodega/2