GET http://localhost:8080/productoStock

###

GET http://localhost:8080/productos


###

GET http://localhost:8080/producto/10

###

POST http://localhost:8080/producto
Content-Type: application/json

{
    "nombre": "",
    "descripcion": "",
    "precio": "",
    "imagen": ""
}

###

put http://localhost:8080/producto/13
Content-Type: application/json

{
    "nombre": "1",
    "descripcion": "",
    "precio": "",
    "imagen": ""
}

###

DELETE http://localhost:8080/producto/14