GET http://localhost:8080/usuarios

###

GET http://localhost:8080/usuario/admin@admin

###

POST http://localhost:8080/usuario
Content-Type: application/json

{
    "correo": "ben.barrientos@duocuc.cl",
    "nombre": "Benjamin",
    "apellido": "Barrientos",
    "contrasena": "12345678",
    "tipo_cuenta": 1

}

###

PUT http://localhost:8080/usuario/ben.barrientos@duocuc.cl
Content-Type: application/json

{
    "correo": "test@test.com",
    "nombre": "Benjamin",
    "apellido": "Barrientos",
    "contrasena": "12345678",
    "tipo_cuenta": 1

}

###

DELETE http://localhost:8080/usuario/test@test.com
