GET http://localhost:8080/ventas

###

GET http://localhost:8080/venta/2

###

POST http://localhost:8080/venta
Content-Type: application/json

{
    "total_venta": 0,
    "orden_compra": "jnasjldgf",
    "correo": "admin@admin"

}

###

PUT http://localhost:8080/venta/7
Content-Type: application/json

{
    "total_venta": 1,
    "correo": "test@test.com"

}

###

DELETE http://localhost:8080/venta/8
